sudo: false
language: java
jdk:
- oraclejdk8

script: mvn clean install
after_success:
- bash <(curl -s https://codecov.io/bash)  
- bash .travis/environment.sh

deploy:
  provider: releases
  api_key:
    secure: kBrM3R+X0/uxUuLk/4USDakywl96Jbd3W5WtQqqZJIgSDBf6T4BHVTYE0YTzh4cndyB0y6QxiHtn1Tm56fpUL/p+tTpTZl6vXbCHI1Vn1RnEKnZK5VtAxeAiTHlBSnohF4DQjOfGtjRcSsRD3Oi9sIXLKBrite0tipzuNNCta0MXMUIXqV9UKIvyIqZkHg1zNrd6z0DVc7/dZDsReAy0whwFRH7bP0YYwyfOU9LdPH2uzedmrUztzvXk3UgdG7BP27TlacxnRE5X81Xxe2HHUCnZZUeAGDyfzJ+KRlmYRty8kfQRiomCdN0V02sO3pHofjGVEF6h+XjVG3uow+KT5peu0YqhfD6JO4dSGIJQ3ozF9QLfPxY/nDyObiETQ875QQpQz7rciYd2fCSgrplXZ5m7LRDa5BM9sUf7S50sjpzHT7Y4ncrrPzmSOajI0wcwM19p9vqcqFyZTCa2AJ99npVaefQxhjFYax6g9o+6JeuWkdjhyNldvVyEqiJjXDM5TxzXMPliU/Jgoy0glh9Nsz5r+qbZAP9DvjVo9NjgCxzPA9ORt+GXWSO95Xe2i9JyItFY6nZBER4fpMnjpSG0oXjJBTZDQnL4NRe7JZc4efSUiL3IfDaWY6+khLmyGh6wO5WOLR93CU7cE47hx5rjpPNyRYXwQWQNYSbtaFSWv0k=
  file: target/release/ACLIB.jar
  skip_cleanup: true    
  on:
    tags: true  
  
notifications:
  email: false

env:    
  global:
  - ENCRYPTION_LABEL: 5795a2fbb362
  - COMMIT_AUTHOR_EMAIL: juli_sesena@hotmail.com
  - secure: "oW2Dkg4Z8lJM9xGP/uky/lCwNBzEZ0gJIO94s1ukWnSmGJG7gWUYdMHwJngXGvgLGNBJPEc4lRi4Pw4SWJUpQ8uKU6XYdfBiphqr7QQixExlgxbIv7qNK02CzeIUxAAJvXePnkQfHZy0fO3Rf97mH1NPY6NYU7ErXHwlYUokidXWHw/N8lu6kMcZUVkosjWu4mTncUmkkbETuXUEnEbdVVhDQede9H8pTa8x3XzZMzBFXDmBdNzX8GjLCfzdBMeb7MH6wsOpQfHOdvuCFn03vUqUIC0WIPVAkYbzPiw/+vNNNLVLqlhCQw7d3P/JdWczKUwxssBnhFaXY9+5jFyk98LWfu3pRgPU1tuccv8Ji3caUt2WwVyA6XBYb4smYIWrQZ7GBWyXX0hrZTDwnrTiQu4lFC2kWC5A+MIGq0mI/f9+rAKd0X5yFkBzoUYzBDZywR6W9yCZiDkv8gEUZFOUXGpLUFAxKTvvuARGvWx5r0iLPhWDXYHcc8EWYio2Bn1DeeXjYgzMYIKxJP4JvYy9ezpN2CPF6A8promFtSn/sjgJYXjsqOEqobrcIWvCZEFd5oRrVQXt0zhvz7JxX6mrgf6zW57S18C4iGnfIBS6A+ZtPDWsC96q4yqrcpGk2GYhA3l5+YgJvrupFcnNCGA7faKgUbLoIJFZxt/Q+tT75l4="
  - secure: "hgJiSALbHEIzGgZMNPzALsgEIuwWJ6ImpC4+4eAz+tX7XYjjwHNA+DHYmPfANn4RcDqs2IHZyQXXXRXib73rBhneIjRYpcM1pH6aU+0lMX8bIXBaSQMEIXT70RYj+OXQKOCvCbOE48dwk3LbQb9CplXZvmT5+QYC9mlt/SBIa78n2ADn8Pl+B9HbAmVmG1D6WgUWuQ0mtLeslfQo8opPIUtUDXPMa8qFpPkLQGrkZsVuZd/l2VWoTRfkFzm0Z8a2dDPoiTYTMv9MoiGLLX6ml2Lt6/v4RV/sPuNeOO6+ax1rSpCHz4uOAxV+51uu2GRrZ6V8/d3VS80bylkgJh4Yn6AfMA6eObiYa8Ei93OuzjMYLhWKEIJAKPxvHUlnFjkvaRgMG3oom0Lkm+pugWY0SDqauG7zQbur+bCeIFp7pPwhv5r51F76ef3RKa02RKCebodW6sna2ke9kxhZf4ZwvWsmXWEn+0h55rH/JYk/NlGcXu2oPzRUG6PUkb58+Mw0E/z12kO3hQOj3bF5zEtiK2YW6mKaRQdXVMW+VEZM5zHzDJr+m/cEw84Qtw2drspJmmBFM5HN/OtiEU5nz2c6uNw/Hp0rQmZTmrIFx5L1eWK6wv/xQec9N38iL8cTuTlIUVbX3AARy8NJG6yAST8ema/WkSVujDqD3VmfYnEarCc="