sudo: false
language: java
jdk:
  - openjdk7

script: mvn clean install
after_success:
  - bash <(curl -s https://codecov.io/bash)  
  - bash .utility/environment.sh

deploy:
  provider: releases
  api_key:
    secure: IvGhdAPT5lRigfuK7yb7idGnokj9myCc8bu2WDk0tIGDsfhRp151nNFO0oues8yyFrcnwvcD25HxIC+illr9RtKU7viUTZtp5QwfnYdWPQaeSMIenlDOEjDzo9FfVMZ7mRAOOlhlZha5ZNQ1PnT0WHHMw0y1LHN7fJz2KiQjHMlcaOdg+8Fb5tYGbH2doaeKirCK80mHtWfb4mBOYBCR/wb0e/ZDl5ctf7bwVZhrH2jOwPkJuqKiUeaqCOUIYEZRHkiAme2FduluGDDMn+4e1FFtO8l8ug7gGzbC54ZmpOy/zSvbi1KGF553KUw+BNuxOVg5Y0MPEQV8u8htG43Z4xuPs5hs36w41zg+N6QiwjyjTlf97q7DgQViaR61iLqpfDbp55Fo3aNycUm+i+xOrqd6Epv8KxwbiVDI+nEbQoHe/KwVZI84t1owqsf/YDkcjVUqHe1BlNyr9qaXR4K5wR2kKLWQuCi57GflqXZISHmbO8hNl0dhORCJtWUAKYu24vDOW1PSdhnIlS6FM+FxgCu0UOCwhBd9ni1nvloxe1ZOmjRloD2sU8+3eWslI3e8oOjHpdYEx4q5tLvdsR12jgDtVkPmGikr6Cq3SxqmWxsNAFxyV+eMTSnvZop1FGEqLizfopvc5PlrlhDnHmy3buhpie93IA5dv2cBiq9H4/U=
  file: target/release/ACLIB.jar
  on:
    tags: true  
  
notifications:
  email: false

env:    
  global:
  - secure: "f3OPEeqts2DLoD3EI90v5CgHNhi3ns6BeNnDobjTo/RCK6suK2M42R4l4LMk3qC50XAlxB87Usb8koGMCqFdS4jdzWJXK9rA8FIjz6Z6xr4AOFnoctXwsipNekqxeOTskuNN5TwGDDucoDWPXWYXpjN1yzmGb+ZO9VfbmwbejKxRhdsL/JXxZ1DSVe4XEyFlPxl6Rz4Zy3OtKYKIyyQAMHH/ZSermA+K+UpWs6zuOwsRoACkoOhOgyTU1Yzg7+i+41LGVcFyVybdZR9M8bDM4CrXcZJFCXwT/cRqVWFGuiSbQZyJZVQDtxbR0Ba/JTSUQWpXi+H35HAMTKqJ6gy4zfBn00lLyrjjca0hdO6ZcTkT88G9pHsoLP4CKNU4LB5hb1YiWqyDp7qNndKUOPFUIJOTnbQjG4oI7vgo8AlmOPqC/RjgEV9q9z8YJlAZtitq7uOnCcJpX4sNNAzu1voUq71i1xaBB21TbnJEn1ggkCrFNuhz0wx7mzgn/dNz9CiBV3XnNJkKEXhbMD5j5TZsjfsHeEzHfhEsXJlCZv+qB8bGuTnpTt49wWa94JSSGzsnEzqW+Ire+j8YeJG9AetABESbXWV5rUZFL1QKVnJCC5zWg5ZCO20EikMSba8RQnzpi9LBag/TP8wf4rKcI6eqUIksbHAikuViHwLtjlUy08k="
  - secure: "oW2Dkg4Z8lJM9xGP/uky/lCwNBzEZ0gJIO94s1ukWnSmGJG7gWUYdMHwJngXGvgLGNBJPEc4lRi4Pw4SWJUpQ8uKU6XYdfBiphqr7QQixExlgxbIv7qNK02CzeIUxAAJvXePnkQfHZy0fO3Rf97mH1NPY6NYU7ErXHwlYUokidXWHw/N8lu6kMcZUVkosjWu4mTncUmkkbETuXUEnEbdVVhDQede9H8pTa8x3XzZMzBFXDmBdNzX8GjLCfzdBMeb7MH6wsOpQfHOdvuCFn03vUqUIC0WIPVAkYbzPiw/+vNNNLVLqlhCQw7d3P/JdWczKUwxssBnhFaXY9+5jFyk98LWfu3pRgPU1tuccv8Ji3caUt2WwVyA6XBYb4smYIWrQZ7GBWyXX0hrZTDwnrTiQu4lFC2kWC5A+MIGq0mI/f9+rAKd0X5yFkBzoUYzBDZywR6W9yCZiDkv8gEUZFOUXGpLUFAxKTvvuARGvWx5r0iLPhWDXYHcc8EWYio2Bn1DeeXjYgzMYIKxJP4JvYy9ezpN2CPF6A8promFtSn/sjgJYXjsqOEqobrcIWvCZEFd5oRrVQXt0zhvz7JxX6mrgf6zW57S18C4iGnfIBS6A+ZtPDWsC96q4yqrcpGk2GYhA3l5+YgJvrupFcnNCGA7faKgUbLoIJFZxt/Q+tT75l4="
  - secure: "hgJiSALbHEIzGgZMNPzALsgEIuwWJ6ImpC4+4eAz+tX7XYjjwHNA+DHYmPfANn4RcDqs2IHZyQXXXRXib73rBhneIjRYpcM1pH6aU+0lMX8bIXBaSQMEIXT70RYj+OXQKOCvCbOE48dwk3LbQb9CplXZvmT5+QYC9mlt/SBIa78n2ADn8Pl+B9HbAmVmG1D6WgUWuQ0mtLeslfQo8opPIUtUDXPMa8qFpPkLQGrkZsVuZd/l2VWoTRfkFzm0Z8a2dDPoiTYTMv9MoiGLLX6ml2Lt6/v4RV/sPuNeOO6+ax1rSpCHz4uOAxV+51uu2GRrZ6V8/d3VS80bylkgJh4Yn6AfMA6eObiYa8Ei93OuzjMYLhWKEIJAKPxvHUlnFjkvaRgMG3oom0Lkm+pugWY0SDqauG7zQbur+bCeIFp7pPwhv5r51F76ef3RKa02RKCebodW6sna2ke9kxhZf4ZwvWsmXWEn+0h55rH/JYk/NlGcXu2oPzRUG6PUkb58+Mw0E/z12kO3hQOj3bF5zEtiK2YW6mKaRQdXVMW+VEZM5zHzDJr+m/cEw84Qtw2drspJmmBFM5HN/OtiEU5nz2c6uNw/Hp0rQmZTmrIFx5L1eWK6wv/xQec9N38iL8cTuTlIUVbX3AARy8NJG6yAST8ema/WkSVujDqD3VmfYnEarCc="